input_template = {' Start_Port_Id': 0,
 ' End_Port_Id': 0,
 ' Total_Distance': 0,
 'Dwt': 0,
 ' Avg_Actual_Speed_Logged': 0,
 'average_ME_mcr': 0,
 'Calm': 0,
 'Smooth': 0,
 'Slight': 0,
 'Moderate': 0,
 'Rough': 0,
 'Very rough': 0,
 'High': 0,
 'Very high': 0,
 'Phenomenal': 0,
 'Vessel_Type_Chemical/Oil Tanker': 0,
 'Vessel_Type_Container Ship': 0,
 'Vessel_Type_General Cargo Ship': 0,
 'Vessel_Type_LNG Carrier': 0,
 'Vessel_Type_LPG Carrier': 0,
 'Vessel_Type_Oil Tanker': 0,
 'Vessel_Type_Ro-Ro Ship': 0,
 'Vessel_Type_Specialised Ship': 0,
 'Sub_Type_Bulk Carrier': 0,
 'Sub_Type_Chemical/Oil Products Tanker IMO-1': 0,
 'Sub_Type_Chemical/Oil Products Tanker IMO-2': 0,
 'Sub_Type_Chemical/Oil Products Tanker IMO-3': 0,
 'Sub_Type_Container Ship (Fully Cellular)': 0,
 'Sub_Type_Crude Tanker': 0,
 'Sub_Type_Crude/Oil Products Tanker': 0,
 'Sub_Type_General Cargo Self-unloader Ship': 0,
 'Sub_Type_LNG DF Diesel (XDF/MEGI)': 0,
 'Sub_Type_LNG Diesel': 0,
 'Sub_Type_LPG Ethylene Carrier': 0,
 'Sub_Type_LPG Fully Refrigerated': 0,
 'Sub_Type_LPG Semi Pressurized': 0,
 'Sub_Type_Ore Carrier': 0,
 'Sub_Type_Ore-Bulk-Oil Carrier': 0,
 'Sub_Type_Products Tanker': 0,
 'Sub_Type_Ro-Ro Cargo Ship': 0}