input_template = {' Start_Port_Id': 0,
 ' End_Port_Id': 0,
 ' Total_Distance': 0,
 'Length': 0,
 'Breadth': 0,
 'Depth': 0,
 'Draft': 0,
 'Grt': 0,
 'Dwt': 0,
 ' Total_Cargo_Onboard': 0,
 ' Cargo_Mt': 0,
 ' Avg_Actual_Speed_Logged': 0,
 ' Avg_Draft_Fore': 0,
 ' Avg_Draft_After': 0,
 'Avg_Displacement': 0,
 ' Tot_ME_Run_Hours': 0,
 'Log_Time_Duration': 0,
 'Avg_AE_Power': 0,
 'Vessel_Type_Chemical/Oil Tanker': 0,
 'Vessel_Type_Container Ship': 0,
 'Vessel_Type_General Cargo Ship': 0,
 'Vessel_Type_LNG Carrier': 0,
 'Vessel_Type_LPG Carrier': 0,
 'Vessel_Type_Offshore Support': 0,
 'Vessel_Type_Oil Tanker': 0,
 'Vessel_Type_Ro-Ro Ship': 0,
 'Vessel_Type_Specialised Ship': 0,
 'Sub_Type_Asphalt/Bitumen Tanker': 0,
 'Sub_Type_Bulk Carrier': 0,
 'Sub_Type_Chemical/Oil Products Tanker IMO-1': 0,
 'Sub_Type_Chemical/Oil Products Tanker IMO-2': 0,
 'Sub_Type_Chemical/Oil Products Tanker IMO-3': 0,
 'Sub_Type_Container Ship (Fully Cellular)': 0,
 'Sub_Type_Crude Tanker': 0,
 'Sub_Type_Crude/Oil Products Tanker': 0,
 'Sub_Type_General Cargo Self-unloader Ship': 0,
 'Sub_Type_General Cargo Ship': 0,
 'Sub_Type_LNG Bunker Vessel': 0,
 'Sub_Type_LPG Ethylene Carrier': 0,
 'Sub_Type_LPG Fully Pressurized': 0,
 'Sub_Type_LPG Fully Refrigerated': 0,
 'Sub_Type_LPG Semi Pressurized': 0,
 'Sub_Type_Ore Carrier': 0,
 'Sub_Type_Ore-Bulk-Oil Carrier': 0,
 'Sub_Type_Products Tanker': 0,
 'Sub_Type_Ro-Ro Cargo Ship': 0}


